### ISSUE TITLE
[FEATURE] Add user documentation and examples

### ISSUE THREAD

**Issue by williamfgc** [nkallima/sim-universal-construction#31]
**Is your feature request related to a problem? Please describe.**
Not related to a problem per-se, but first time users can benefit for more comprehensive and clear documentation.

**Describe the solution you'd like**
Add user documentation. While there is a substantial amount of documentation in the [README.md](https://github.com/nkallima/sim-universal-construction/blob/master/README.md) a more comprehensive document would benefit the user that want more detail. 

**Describe alternatives you've considered**
GitHub pages, ReadTheDocs, also providing functional examples could help the interested user for reproducibility of the claimed performance and functionality

**Additional context**
Some more specific points to be addressed and be clear about up front in the docs (possibly in README.md) to give a clear scope to the potential user:

- [x] Indicate if this is a library, executable. If it's a C library as it seems to be the case from the API example, please add a prefix_ "namespace" (e.g. `synch_foo`) to library API functions to avoid name clashes
- [x] Indicate this is a Linux-only library
- [x] What's the baseline used for performance claims? Is it measuring strong/weak scalability?
- [x] Illustrate examples comparing this implementation with existing implementations to justify performance (e.g. C++ `std::queue`, `std::unordered_map` for hash-table, C++ <thread> etc?) to users know what to expect in terms of performance.

Related to [JOSS review 3143](https://github.com/openjournals/joss-reviews/issues/3143)

**Comment by nkallima** [comment]
>Describe the solution you'd like
>Add user documentation. While there is a substantial amount of documentation in the >README.md a more comprehensive document would benefit the user that want more detail.

In the v2.5.0 branch (it will be released to the master branch whenever it is in a good shape), I have started creating documentation for the provided API (i.e. all the header files under the libconcurrent/includes/ directory). Until now, a substantial set of the provided API is documented; however, a few files remain to be documented. 

>Describe alternatives you've considered
>GitHub pages, ReadTheDocs, also providing functional examples could help the interested user for reproducibility of the claimed performance and functionality

Currently, the provided documentation is produced by Doxygen creating man-pages  (check https://github.com/nkallima/sim-universal-construction/tree/v2.5.0-dev#configuring-compiling-and-installing-the-framework for more), which is a bit old-fashioned.
I will check if there is an easy way to move a part of the documentation to GitHub pages or ReadTheDocs as you suggested.

> Indicate if this is a library, executable. If it's a C library as it seems to be the case from the API example, please add a prefix_ "namespace" (e.g. synch_foo) to library API functions to avoid name clashes

This is a good idea, at least for the basic functionality provided by the runtime and the primitives. However, I’m a bit skeptical to adopt it for all the provided concurrent algorithms, since the API of some data-structures is a bit old and I hesitate to change the naming scheme. In any case, it’s a good idea to start changing the runtime and primitives naming.

**Comment by williamfgc** [comment]
> However, I’m a bit skeptical to adopt it for all the provided concurrent algorithms

Fair point, let me clarify my initial request. The public facing API should have a prefix (what users are supposed to "consume"), everything that has a private scope is fine. Let me know if this makes any sense. Thanks for addressing the other points!

**Comment by nkallima** [comment]
@williamfgc Yes, I agree and I will revise the naming soon.

**Comment by nkallima** [comment]
@williamfgc

>  What's the baseline used for performance claims? Is it measuring strong/weak scalability?
>  Illustrate examples comparing this implementation with existing implementations to justify performance (e.g. C++ std::queue, std::unordered_map for hash-table, C++ etc?) to users know what to expect in terms of performance.

I have added a new document that describes the expected performance of various objects/data-structures provided by the framework. It also provides some indicative performance measurements. Please check  https://github.com/nkallima/sim-universal-construction/blob/v2.5.0-dev/PERFORMANCE.md.
Moreover, README.md and PERFORMANCE.md clearly state that strong scaling is measured.

**Comment by nkallima** [comment]
@williamfgc

> Indicate if this is a library, executable. If it's a C library as it seems to be the case from the API example, please add a prefix_ "namespace" (e.g. synch_foo) to library API functions to avoid name clashes

I have added a `synch` prefix for the provided functions of the public API. I also added the `Synch` prefix for the public structs. A first version of this new naming scheme can be found in the v3.0.0-dev branch  https://github.com/nkallima/sim-universal-construction/tree/v3.0.0-dev. Given that the new version of the API is incompatible with the previous versions, I had to increase the major number of the version to 3.
However, this naming scheme introduces the following issues:

* The functions’ naming for some of the provided objects are weird. For example, the `CCSynchStructInit` function of the CC-Synch object converts to `synchCCSynchStructInit`, which is a bit weird since there are two instances of the `synch`. The same holds for a few other objects such as H-Synch, DSM-Synch, etc.
 * It creates confusion to some cases. For example the `SimStructInit` function for the Sim combining object converts to `synchSimStructInit`. This may confuse a user for which object the `synchSimStructInit` function stands for, Sim or  CC-Synch? This holds for a lot of objects.
For these problems, I thought of the following three solutions:
1. Leaving the API as is in the v3.0.0-dev branch.
2. For all functions for the runtime part of the framework (i.e, functions for creating threads, functions for managing memory, etc.), the `synch` prefix could be adopted. The legacy naming (without the `synch` prefix) could be used only for the concurrent objects, e.g. CC-Synch, Sim, etc.
3. Keeping the API of v2.x.y versions.

In my opinion, 2 seems to be a balanced trade-off. What do you think?

**Comment by williamfgc** [comment]
@nkallima thanks for addressing this. Yes, 2 sounds good. It's just for early awareness, so this issue doesn't pop in the future with potential users. Thanks!

**Comment by nkallima** [comment]
@williamfgc thanks for your feedback! The revised API is now available at v.3.0.0-dev branch (https://github.com/nkallima/sim-universal-construction/tree/v3.0.0-dev).
In case that you are OK with the changes, we could close this issue.

**Comment by williamfgc** [comment]
Thanks @nkallima, closing...
